name: Build
on: [push]
env:
  PYTHON_VERSION: 3.10.5
jobs:
  lint:
    name: Lints the code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Black
        run: pipenv run black --check
  test:
    name: Runs unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Test
        run: pipenv run pytest
  build-and-publish-container:
    name: Build and publish container to Docker Hub
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata and tags for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ianwestfall/sources_bot
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: ${{ github.ref_name == 'main' }} # Only push to Dockerhub if this is the main branch
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
